INSERT INTO product(`name`,`price`,`provider`,`description`) VALUES("pot",0.0,"jiffy","pots");
INSERT INTO product(`name`,`price`,`provider`,`description`) VALUES("soil pellet",0.0,"jiffy","soil pellet");
INSERT INTO product(`name`,`price`,`provider`,`description`) VALUES("plant marker",0.0,"mastertag","plant markers");
INSERT INTO product(`name`,`price`,`provider`,`description`) VALUES("polybag for soil",0.0,"amazon","polybag for soil");
INSERT INTO product(`name`,`price`,`provider`,`description`) VALUES("master carton",0.0,"office depot","master carton - can hold up to 24 units");
INSERT INTO product(`name`,`price`,`provider`,`description`) VALUES("bonsai instructions",0.0,"china","bonsai instructions");
INSERT INTO product(`name`,`price`,`provider`,`description`) VALUES("bonsai packaging box",0.0,"china","bonsai packaging boxe");
INSERT INTO product(`name`,`price`,`provider`,`description`) VALUES("jacaranda seed packet",0.0,"page seed","jacranda packet");
INSERT INTO product(`name`,`price`,`provider`,`description`) VALUES("Delonix seed packet",0.0,"page seed","Delonix seed packet");
INSERT INTO product(`name`,`price`,`provider`,`description`) VALUES("Picea seed packet",0.0,"page seed","Picea seed packet");
INSERT INTO product(`name`,`price`,`provider`,`description`) VALUES("Pinus seed packet",0.0,"page seed","Pinus seed packet");
INSERT INTO product(`name`,`price`,`provider`,`description`) VALUES("herb instructions",0.0,"china","herbs instructions");
INSERT INTO product(`name`,`price`,`provider`,`description`) VALUES("herb packaging box",0.0,"china","herb packaging box");
INSERT INTO product(`name`,`price`,`provider`,`description`) VALUES("basil",0.0,"page seed","basil seed packet");
INSERT INTO product(`name`,`price`,`provider`,`description`) VALUES("sage",0.0,"page seed","sage seed packet");
INSERT INTO product(`name`,`price`,`provider`,`description`) VALUES("parsley",0.0,"page seed","parsley seed packet");
INSERT INTO product(`name`,`price`,`provider`,`description`) VALUES("thyme",0.0,"page seed","thyme seed packet");
INSERT INTO product(`name`,`price`,`provider`,`description`) VALUES("cilantro",0.0,"page seed","cilantro seed packet");
INSERT INTO product(`name`,`price`,`provider`,`description`) VALUES("Crazy garden instructions",0.0,"china","Crazy garden instructions");
INSERT INTO product(`name`,`price`,`provider`,`description`) VALUES("Crazy garden packaging box",0.0,"china","Crazy garden packaging box");
INSERT INTO product(`name`,`price`,`provider`,`description`) VALUES("Purple carrot",0.0,"Page seed","Purple carrot seed packet");
INSERT INTO product(`name`,`price`,`provider`,`description`) VALUES("Black corn",0.0,"Page seed","Black corn seed packet");
INSERT INTO product(`name`,`price`,`provider`,`description`) VALUES("Lemon cucumber",0.0,"Page seed","Lemon cucumber seed packet");
INSERT INTO product(`name`,`price`,`provider`,`description`) VALUES("5 color swiss chard",0.0,"Page seed","5 Color swiss chard seed packet");
INSERT INTO product(`name`,`price`,`provider`,`description`) VALUES("Romanesco Brocolli",0.0,"Page seed","Romanesco Brocolli seed packet");