INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(282, "pot marigold",0.0,150,"Page seed","pot marigold");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(292, "viola tricolor",0.0,150,"Page seed","viola tricolor");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(302, "cornflower",0.0,150,"Page seed","cornflower");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(402, "shasta daisy",0.0,150,"Page seed","shasta daisy");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(412, "edible flowers packaging box",0.0,150,"Page seed","edible flowers packaging box");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(422, "edible flowers instructions",0.0,150,"Page seed","edible flowers instructions");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(432, "kale",0.0,150,"Page seed","kale");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(442, "beets",0.0,150,"Page seed","beets");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(452, "leeks",0.0,150,"Page seed","leeks");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(462, "brussle sprout",0.0,150,"Page seed","brussle sprout");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(472, "super foods packaging box",0.0,150,"Page seed","super foods packaging box");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(482, "super foods instructions",0.0,150,"Page seed","super foods instructions");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(492, "mint",0.0,150,"Page seed","mint");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(502, "chamomile",0.0,150,"Page seed","chamomile");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(512, "lemon balm",0.0,150,"Page seed","lemon balm");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(522, "catnip",0.0,150,"Page seed","catnip");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(532, "herbal tea packaging box",0.0,150,"Page seed","herbal tea packaging box");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(542, "herbal tea instructions",0.0,150,"Page seed","herbal tea instructions");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(552, "blackberry",0.0,150,"Page seed","blackberry");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(562, "blueberry",0.0,150,"Page seed","blueberry");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(572, "raspberry",0.0,150,"Page seed","raspberry");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(582, "gojiberry",0.0,150,"Page seed","gojiberry");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(592, "fruits packaging box",0.0,150,"Page seed","fruits packaging box");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(602, "fruits instructions",0.0,150,"Page seed","fruits instructions");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(612, "jalapeno",0.0,150,"Page seed","jalapeno");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(622, "yellow pepper",0.0,150,"Page seed","yellow pepper");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(632, "sweet red pepper",0.0,150,"Page seed","sweet red pepper");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(642, "cayenne",0.0,150,"Page seed","cayenne");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(652, "pepper packaging box",0.0,150,"Page seed","pepper packaging box");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(662, "pepper instructions",0.0,150,"Page seed","pepper instructions");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(672, "aragula",0.0,150,"Page seed","aragula");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(682, "basil",0.0,150,"Page seed","basil");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(692, "beets",0.0,150,"Page seed","beets");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(702, "5 color swiss chard",0.0,150,"Page seed","5 color swiss chard");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(712, "micro greens packaging box",0.0,150,"Page seed","micro greens packaging box");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(722, "micro greens instructions",0.0,150,"Page seed","micro greens instructions");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(732, "delicious red",0.0,150,"Page seed","delicious red");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(742, "green zebra",0.0,150,"Page seed","green zebra");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(752, "yellow pear",0.0,150,"Page seed","yellow pear");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(762, "blue cherry",0.0,150,"Page seed","blue cherry");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(772, "tomato packaging box",0.0,150,"Page seed","tomato packaging box");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(782, "tomato instructions",0.0,150,"Page seed","tomato instructions");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(792, "radish",0.0,150,"Page seed","radish");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(802, "tomato",0.0,150,"Page seed","tomato");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(812, "lettuce",0.0,150,"Page seed","lettuce");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(822, "cucumber",0.0,150,"Page seed","cucumber");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(832, "heirloom salad packaging box",0.0,150,"Page seed","heirloom packaging box");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(842, "heirloom salad instructions",0.0,150,"Page seed","heirloom salad instructions");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(852, "thank you slip",0.0,500,"moly","moly");
INSERT INTO product(`product_id`, `name`,`price`,`required_count_red`, `provider`,`description`) VALUES(862, "polybag",0.0,1000,"poly","poly");


